public class UserAccount extends DatabaseObject {
    private String Email;
    private String UserID;
    private String Bankname;
    private String Kontonummer;
    private String Adresse;
    UserAccount(String Email, String Bankname, String Kontonummer, String Adresse){
        this.Email = Email;
        this.Bankname = Bankname;
        this.Kontonummer = Kontonummer;
        this.Adresse = Adresse;
        this.UserID = "NULL"; // generated by sequence oin oracle db
    }

    public String getEmail() {
        return Email;
    }

    public String getUserID() {
        return UserID;
    }

    public String getBankname() {
        return Bankname;
    }

    public String getKontonummer() {
        return Kontonummer;
    }

    public String getAdresse() {
        return Adresse;
    }

    @Override
    public int compareTo(Object o) {
        if (o instanceof UserAccount) return getEmail().compareTo(((UserAccount) o).getEmail());
        else throw new ClassCastException("Incompatible types for UserAccount.compareTo(Object o).");
    }


    @Override
    public String toString() {
        return "UserAccount{" +
                "Email='" + Email + '\'' +
                ", UserID='" + UserID + '\'' +
                ", Bankname='" + Bankname + '\'' +
                ", Kontonummer='" + Kontonummer + '\'' +
                ", Adresse='" + Adresse + '\'' +
                '}' + '\n';
    }
}